### ISSUE TITLE
Tracking for project outline view

### ISSUE THREAD

**Issue by seresl** [YsuSERESL/iTrace#2] opened 2014-09-15 06:26 UTC
Keep track of when eye gaze falls on the project outline view in Eclipse.

**Comment by shbonita** [comment] 2016-02-05 05:25
@jennalwise has this issue been resolved? I believe it has.  If so, can we close it?

**Comment by jennalwise** [comment] 2016-02-05 06:35
The problem that we were having with Tim's code for this issue should be resolved now. We still need to test it and merge it. Then the issue will be resolved.

**Comment by shbonita** [comment] 2016-09-16 14:28
Jenna said:
I found a problem with the handleGaze method and UIJob method in the ControlView. One of them is using Monitor bounds and the other is using the Screen bounds from somewhere else. These two bounds do not line up (screen bounds gives you the proper resolution for your screen and the other gives you like half those resolutions (it is the bounds for the rootshell in eclipse). I changed the UIJob method to use the Monitor bounds instead of the Screen bounds and everything looks okay/fixed (although I didn't test it thoroughly). In general, I am not sure about using the Monitor bounds and what exactly three lines of code in the HandleGaze method is doing when it uses them. I don't have time to find out, so I left commented out print statements and a comment about what to look into in my most recent commit in branch issue2.

I don't think using Monitor bounds is correct, so my possible fix is sketchy and I would like someone to take a look at it while I am gone. Especially because this bug will cause problems with master's implementation and accuracy with respect to AST documents.

@onebenclark  please check what Jenna is asking.

**Comment by jennalwise** [comment] 2016-09-25 14:50
Using the Monitor bounds is the correct solution. This bug is only able to be reproduced on higher level displays/resolutions where Windows 10 recommends all text, apps, etc. be re-scaled by 200% (usually on 2560 x 1440 resolutions, ie. my laptop). This causes a discrepancy between the system's resolution and the resolution used by Eclipse (at 200% the resolution for Eclipse is re-scaled to 1280 x 720). Since the gazes are normalized there isn't a problem with using Eclipse's resolution vs. the system's resolution. Actually, it is proper to use Eclipse's resolution, because the displayed Eclipse UI elements depends on Eclipse's resolution.

I still have a small issue with two lines of code that I believe have a useless subtraction in them (at least for one display/monitor). I won't be able to see if it is actually useful until I get into the lab and test it on multiple displays.

Otherwise, this issue needs tested and merged.

**Comment by jennalwise** [comment] 2016-09-25 17:34
Found a problem with the browser editor not having an adaptable control. I need to spend some time figuring out how to retrieve the associated browser control from an editor part in the most painless way.

**Closed as completed** 2018-11-01 18:44 UTC
Labels: enhancement, high priority
